version: '3.8'

services:
  web:
    container_name: banking
    build:
      context: .
    image: banking-system
    command: /bin/sh -c "go run server.go"
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
        - data-sql:/var/lib/postgresql

volumes:
  data-sql:
    driver: local